targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/graphql/**
      - general.schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: general.schema.graphql
              queries_glob: lib/graphql/general/*.graphql
              output: lib/generatedql/general/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/auth/*.graphql
              output: lib/generatedql/auth/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/user/*.graphql
              output: lib/generatedql/user/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/address/*.graphql
              output: lib/generatedql/address/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/cart/*.graphql
              output: lib/generatedql/cart/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/products/*.graphql
              output: lib/generatedql/products/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/cartegoies/*.graphql
              output: lib/generatedql/cartegoies/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/related_product/*.graphql
              output: lib/generatedql/related_product/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/ratings/*.graphql
              output: lib/generatedql/ratings/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/order_products/*.graphql
              output: lib/generatedql/order_products/graphql_api.dart
            - schema: general.schema.graphql
              queries_glob: lib/graphql/orders/*.graphql
              output: lib/generatedql/orders/graphql_api.dart