name: mmd_ecommerce_fl_lib
description: It is a backend library using GraphQl to facilitate connection to our different e-commerce backend endpoints.
version: 0.0.3
homepage: https://github.com/BeshoyMelika/mmd-ecommerce-fl-lib

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.2.3
  equatable: ^1.0.2
  gql: ^0.12.0
  meta: '>=1.0.0 <2.0.0' # only if you have non nullable fields
  path_provider: ^1.5.1
  graphql_flutter: ^3.1.0
  analyzer: ^0.39.2+1
  artemis: ^2.1.4
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  build_resolvers: ^1.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
    # This plugin project was generated without specifying any
    # platforms with the `--platform` argument. If you see the `fake_platform` map below, remove it and
    # then add platforms following the instruction here:
    # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
    # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------

